version: '3'
services:
  jenkins:
      build: .
      restart: always   
      env_file:
          - jenkins.env
          - sonarqube-deploy.env   
      ports:
          - "8080:8080"
      volumes:
           - /var/run/docker.sock:/var/run/docker.sock:rw
      privileged: true
